## **Loading data into Pandas**

In [0]:
import pandas as pd

In [35]:
df = pd.read_csv('pokemon_data.csv')

print(df.head().T)

                    0        1         2                      3           4
#                   1        2         3                      3           4
Name        Bulbasaur  Ivysaur  Venusaur  VenusaurMega Venusaur  Charmander
Type 1          Grass    Grass     Grass                  Grass        Fire
Type 2         Poison   Poison    Poison                 Poison         NaN
HP                 45       60        80                     80          39
Attack             49       62        82                    100          52
Defense            49       63        83                    123          43
Sp. Atk            65       80       100                    122          60
Sp. Def            65       80       100                    120          50
Speed              45       60        80                     80          65
Generation          1        1         1                      1           1
Legendary       False    False     False                  False       False

## **Reading Data in Pandas**

In [36]:
# Read Headers
print(df.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [37]:
# Read each Column
print(df['Name'][0:5])

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [38]:
print(df[['Name', 'Type 1', 'HP']])

                      Name   Type 1  HP
0                Bulbasaur    Grass  45
1                  Ivysaur    Grass  60
2                 Venusaur    Grass  80
3    VenusaurMega Venusaur    Grass  80
4               Charmander     Fire  39
..                     ...      ...  ..
795                Diancie     Rock  50
796    DiancieMega Diancie     Rock  50
797    HoopaHoopa Confined  Psychic  80
798     HoopaHoopa Unbound  Psychic  80
799              Volcanion     Fire  80

[800 rows x 3 columns]

In [39]:
# Read Each Row
print(df.iloc[1:4].T)

                  1         2                      3
#                 2         3                      3
Name        Ivysaur  Venusaur  VenusaurMega Venusaur
Type 1        Grass     Grass                  Grass
Type 2       Poison    Poison                 Poison
HP               60        80                     80
Attack           62        82                    100
Defense          63        83                    123
Sp. Atk          80       100                    122
Sp. Def          80       100                    120
Speed            60        80                     80
Generation        1         1                      1
Legendary     False     False                  False

In [40]:
# Read a specific location (R,C)
print(df.iloc[2,1])

Venusaur

In [41]:
# Iterating Row by Row
for index, row in df.iterrows():
  print(index, row['Name'])

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey
21 Pidgeotto
22 Pidgeot
23 PidgeotMega Pidgeot
24 Rattata
25 Raticate
26 Spearow
27 Fearow
28 Ekans
29 Arbok
30 Pikachu
31 Raichu
32 Sandshrew
33 Sandslash
34 Nidoran (Female)
35 Nidorina
36 Nidoqueen
37 Nidoran (Male)
38 Nidorino
39 Nidoking
40 Clefairy
41 Clefable
42 Vulpix
43 Ninetales
44 Jigglypuff
45 Wigglytuff
46 Zubat
47 Golbat
48 Oddish
49 Gloom
50 Vileplume
51 Paras
52 Parasect
53 Venonat
54 Venomoth
55 Diglett
56 Dugtrio
57 Meowth
58 Persian
59 Psyduck
60 Golduck
61 Mankey
62 Primeape
63 Growlithe
64 Arcanine
65 Poliwag
66 Poliwhirl
67 Poliwrath
68 Abra
69 Kadabra
70 Alakazam
71 AlakazamMega Alakazam
72 Machop
73 Machoke
74 Machamp
75 Bellsprout
76 Weepinbell
77 Victreebel
78 Tentacool
79 Tentacruel
80 Geodude
81 Graveler
82 Golem
83 Ponyta
84 Rapidash
85 Slowpoke
86 Slowbro
87 SlowbroMega Slowbro
88 Magnemite
89 Magneton
90 Farfetch'd
91 Doduo
92 Dodrio
93 Seel
94 Dewgong
95 Grimer
96 Muk
97 Shellder
98 Cloyster
99 Gastly
100 Haunter
101 Gengar
102 GengarMega Gengar
103 Onix
104 Drowzee
105 Hypno
106 Krabby
107 Kingler
108 Voltorb
109 Electrode
110 Exeggcute
111 Exeggutor
112 Cubone
113 Marowak
114 Hitmonlee
115 Hitmonchan
116 Lickitung
117 Koffing
118 Weezing
119 Rhyhorn
120 Rhydon
121 Chansey
122 Tangela
123 Kangaskhan
124 KangaskhanMega Kangaskhan
125 Horsea
126 Seadra
127 Goldeen
128 Seaking
129 Staryu
130 Starmie
131 Mr. Mime
132 Scyther
133 Jynx
134 Electabuzz
135 Magmar
136 Pinsir
137 PinsirMega Pinsir
138 Tauros
139 Magikarp
140 Gyarados
141 GyaradosMega Gyarados
142 Lapras
143 Ditto
144 Eevee
145 Vaporeon
146 Jolteon
147 Flareon
148 Porygon
149 Omanyte
150 Omastar
151 Kabuto
152 Kabutops
153 Aerodactyl
154 AerodactylMega Aerodactyl
155 Snorlax
156 Articuno
157 Zapdos
158 Moltres
159 Dratini
160 Dragonair
161 Dragonite
162 Mewtwo
163 MewtwoMega Mewtwo X
164 MewtwoMega Mewtwo Y
165 Mew
166 Chikorita
167 Bayleef
168 Meganium
169 Cyndaquil
170 Quilava
171 Typhlosion
172 Totodile
173 Croconaw
174 Feraligatr
175 Sentret
176 Furret
177 Hoothoot
178 Noctowl
179 Ledyba
180 Ledian
181 Spinarak
182 Ariados
183 Crobat
184 Chinchou
185 Lanturn
186 Pichu
187 Cleffa
188 Igglybuff
189 Togepi
190 Togetic
191 Natu
192 Xatu
193 Mareep
194 Flaaffy
195 Ampharos
196 AmpharosMega Ampharos
197 Bellossom
198 Marill
199 Azumarill
200 Sudowoodo
201 Politoed
202 Hoppip
203 Skiploom
204 Jumpluff
205 Aipom
206 Sunkern
207 Sunflora
208 Yanma
209 Wooper
210 Quagsire
211 Espeon
212 Umbreon
213 Murkrow
214 Slowking
215 Misdreavus
216 Unown
217 Wobbuffet
218 Girafarig
219 Pineco
220 Forretress
221 Dunsparce
222 Gligar
223 Steelix
224 SteelixMega Steelix
225 Snubbull
226 Granbull
227 Qwilfish
228 Scizor
229 ScizorMega Scizor
230 Shuckle
231 Heracross
232 HeracrossMega Heracross
233 Sneasel
234 Teddiursa
235 Ursaring
236 Slugma
237 Magcargo
238 Swinub
239 Piloswine
240 Corsola
241 Remoraid
242 Octillery
243 Delibird
244 Mantine
245 Skarmory
246 Houndour
247 Houndoom
248 HoundoomMega Houndoom
249 Kingdra
250 Phanpy
251 Donphan
252 Porygon2
253 Stantler
254 Smeargle
255 Tyrogue
256 Hitmontop
257 Smoochum
258 Elekid
259 Magby
260 Miltank
261 Blissey
262 Raikou
263 Entei
264 Suicune
265 Larvitar
266 Pupitar
267 Tyranitar
268 TyranitarMega Tyranitar
269 Lugia
270 Ho-oh
271 Celebi
272 Treecko
273 Grovyle
274 Sceptile
275 SceptileMega Sceptile
276 Torchic
277 Combusken
278 Blaziken
279 BlazikenMega Blaziken
280 Mudkip
281 Marshtomp
282 Swampert
283 SwampertMega Swampert
284 Poochyena
285 Mightyena
286 Zigzagoon
287 Linoone
288 Wurmple
289 Silcoon
290 Beautifly
291 Cascoon
292 Dustox
293 Lotad
294 Lombre
295 Ludicolo
296 Seedot
297 Nuzleaf
298 Shiftry
299 Taillow
300 Swellow
301 Wingull
302 Pelipper
303 Ralts
304 Kirlia
305 Gardevoir
306 GardevoirMega Gardevoir
307 Surskit
308 Masquerain
309 Shroomish
310 Breloom
311 Slakoth
312 Vigoroth
313 Slaking
314 Nincada
315 Ninjask
316 Shedinja
317 Whismur
318 Loudred
319 Exploud
320 Makuhita
321 Hariyama
322 Azurill
323 Nosepass
324 Skitty
325 Delcatty
326 Sableye
327 SableyeMega Sableye
328 Mawile
329 MawileMega Mawile
330 Aron
331 Lairon
332 Aggron
333 AggronMega Aggron
334 Meditite
335 Medicham
336 MedichamMega Medicham
337 Electrike
338 Manectric
339 ManectricMega Manectric
340 Plusle
341 Minun
342 Volbeat
343 Illumise
344 Roselia
345 Gulpin
346 Swalot
347 Carvanha
348 Sharpedo
349 SharpedoMega Sharpedo
350 Wailmer
351 Wailord
352 Numel
353 Camerupt
354 CameruptMega Camerupt
355 Torkoal
356 Spoink
357 Grumpig
358 Spinda
359 Trapinch
360 Vibrava
361 Flygon
362 Cacnea
363 Cacturne
364 Swablu
365 Altaria
366 AltariaMega Altaria
367 Zangoose
368 Seviper
369 Lunatone
370 Solrock
371 Barboach
372 Whiscash
373 Corphish
374 Crawdaunt
375 Baltoy
376 Claydol
377 Lileep
378 Cradily
379 Anorith
380 Armaldo
381 Feebas
382 Milotic
383 Castform
384 Kecleon
385 Shuppet
386 Banette
387 BanetteMega Banette
388 Duskull
389 Dusclops
390 Tropius
391 Chimecho
392 Absol
393 AbsolMega Absol
394 Wynaut
395 Snorunt
396 Glalie
397 GlalieMega Glalie
398 Spheal
399 Sealeo
400 Walrein
401 Clamperl
402 Huntail
403 Gorebyss
404 Relicanth
405 Luvdisc
406 Bagon
407 Shelgon
408 Salamence
409 SalamenceMega Salamence
410 Beldum
411 Metang
412 Metagross
413 MetagrossMega Metagross
414 Regirock
415 Regice
416 Registeel
417 Latias
418 LatiasMega Latias
419 Latios
420 LatiosMega Latios
421 Kyogre
422 KyogrePrimal Kyogre
423 Groudon
424 GroudonPrimal Groudon
425 Rayquaza
426 RayquazaMega Rayquaza
427 Jirachi
428 DeoxysNormal Forme
429 DeoxysAttack Forme
430 DeoxysDefense Forme
431 DeoxysSpeed Forme
432 Turtwig
433 Grotle
434 Torterra
435 Chimchar
436 Monferno
437 Infernape
438 Piplup
439 Prinplup
440 Empoleon
441 Starly
442 Staravia
443 Staraptor
444 Bidoof
445 Bibarel
446 Kricketot
447 Kricketune
448 Shinx
449 Luxio
450 Luxray
451 Budew
452 Roserade
453 Cranidos
454 Rampardos
455 Shieldon
456 Bastiodon
457 Burmy
458 WormadamPlant Cloak
459 WormadamSandy Cloak
460 WormadamTrash Cloak
461 Mothim
462 Combee
463 Vespiquen
464 Pachirisu
465 Buizel
466 Floatzel
467 Cherubi
468 Cherrim
469 Shellos
470 Gastrodon
471 Ambipom
472 Drifloon
473 Drifblim
474 Buneary
475 Lopunny
476 LopunnyMega Lopunny
477 Mismagius
478 Honchkrow
479 Glameow
480 Purugly
481 Chingling
482 Stunky
483 Skuntank
484 Bronzor
485 Bronzong
486 Bonsly
487 Mime Jr.
488 Happiny
489 Chatot
490 Spiritomb
491 Gible
492 Gabite
493 Garchomp
494 GarchompMega Garchomp
495 Munchlax
496 Riolu
497 Lucario
498 LucarioMega Lucario
499 Hippopotas
500 Hippowdon
501 Skorupi
502 Drapion
503 Croagunk
504 Toxicroak
505 Carnivine
506 Finneon
507 Lumineon
508 Mantyke
509 Snover
510 Abomasnow
511 AbomasnowMega Abomasnow
512 Weavile
513 Magnezone
514 Lickilicky
515 Rhyperior
516 Tangrowth
517 Electivire
518 Magmortar
519 Togekiss
520 Yanmega
521 Leafeon
522 Glaceon
523 Gliscor
524 Mamoswine
525 Porygon-Z
526 Gallade
527 GalladeMega Gallade
528 Probopass
529 Dusknoir
530 Froslass
531 Rotom
532 RotomHeat Rotom
533 RotomWash Rotom
534 RotomFrost Rotom
535 RotomFan Rotom
536 RotomMow Rotom
537 Uxie
538 Mesprit
539 Azelf
540 Dialga
541 Palkia
542 Heatran
543 Regigigas
544 GiratinaAltered Forme
545 GiratinaOrigin Forme
546 Cresselia
547 Phione
548 Manaphy
549 Darkrai
550 ShayminLand Forme
551 ShayminSky Forme
552 Arceus
553 Victini
554 Snivy
555 Servine
556 Serperior
557 Tepig
558 Pignite
559 Emboar
560 Oshawott
561 Dewott
562 Samurott
563 Patrat
564 Watchog
565 Lillipup
566 Herdier
567 Stoutland
568 Purrloin
569 Liepard
570 Pansage
571 Simisage
572 Pansear
573 Simisear
574 Panpour
575 Simipour
576 Munna
577 Musharna
578 Pidove
579 Tranquill
580 Unfezant
581 Blitzle
582 Zebstrika
583 Roggenrola
584 Boldore
585 Gigalith
586 Woobat
587 Swoobat
588 Drilbur
589 Excadrill
590 Audino
591 AudinoMega Audino
592 Timburr
593 Gurdurr
594 Conkeldurr
595 Tympole
596 Palpitoad
597 Seismitoad
598 Throh
599 Sawk
600 Sewaddle
601 Swadloon
602 Leavanny
603 Venipede
604 Whirlipede
605 Scolipede
606 Cottonee
607 Whimsicott
608 Petilil
609 Lilligant
610 Basculin
611 Sandile
612 Krokorok
613 Krookodile
614 Darumaka
615 DarmanitanStandard Mode
616 DarmanitanZen Mode
617 Maractus
618 Dwebble
619 Crustle
620 Scraggy
621 Scrafty
622 Sigilyph
623 Yamask
624 Cofagrigus
625 Tirtouga
626 Carracosta
627 Archen
628 Archeops
629 Trubbish
630 Garbodor
631 Zorua
632 Zoroark
633 Minccino
634 Cinccino
635 Gothita
636 Gothorita
637 Gothitelle
638 Solosis
639 Duosion
640 Reuniclus
641 Ducklett
642 Swanna
643 Vanillite
644 Vanillish
645 Vanilluxe
646 Deerling
647 Sawsbuck
648 Emolga
649 Karrablast
650 Escavalier
651 Foongus
652 Amoonguss
653 Frillish
654 Jellicent
655 Alomomola
656 Joltik
657 Galvantula
658 Ferroseed
659 Ferrothorn
660 Klink
661 Klang
662 Klinklang
663 Tynamo
664 Eelektrik
665 Eelektross
666 Elgyem
667 Beheeyem
668 Litwick
669 Lampent
670 Chandelure
671 Axew
672 Fraxure
673 Haxorus
674 Cubchoo
675 Beartic
676 Cryogonal
677 Shelmet
678 Accelgor
679 Stunfisk
680 Mienfoo
681 Mienshao
682 Druddigon
683 Golett
684 Golurk
685 Pawniard
686 Bisharp
687 Bouffalant
688 Rufflet
689 Braviary
690 Vullaby
691 Mandibuzz
692 Heatmor
693 Durant
694 Deino
695 Zweilous
696 Hydreigon
697 Larvesta
698 Volcarona
699 Cobalion
700 Terrakion
701 Virizion
702 TornadusIncarnate Forme
703 TornadusTherian Forme
704 ThundurusIncarnate Forme
705 ThundurusTherian Forme
706 Reshiram
707 Zekrom
708 LandorusIncarnate Forme
709 LandorusTherian Forme
710 Kyurem
711 KyuremBlack Kyurem
712 KyuremWhite Kyurem
713 KeldeoOrdinary Forme
714 KeldeoResolute Forme
715 MeloettaAria Forme
716 MeloettaPirouette Forme
717 Genesect
718 Chespin
719 Quilladin
720 Chesnaught
721 Fennekin
722 Braixen
723 Delphox
724 Froakie
725 Frogadier
726 Greninja
727 Bunnelby
728 Diggersby
729 Fletchling
730 Fletchinder
731 Talonflame
732 Scatterbug
733 Spewpa
734 Vivillon
735 Litleo
736 Pyroar
737 Flabébé
738 Floette
739 Florges
740 Skiddo
741 Gogoat
742 Pancham
743 Pangoro
744 Furfrou
745 Espurr
746 MeowsticMale
747 MeowsticFemale
748 Honedge
749 Doublade
750 AegislashBlade Forme
751 AegislashShield Forme
752 Spritzee
753 Aromatisse
754 Swirlix
755 Slurpuff
756 Inkay
757 Malamar
758 Binacle
759 Barbaracle
760 Skrelp
761 Dragalge
762 Clauncher
763 Clawitzer
764 Helioptile
765 Heliolisk
766 Tyrunt
767 Tyrantrum
768 Amaura
769 Aurorus
770 Sylveon
771 Hawlucha
772 Dedenne
773 Carbink
774 Goomy
775 Sliggoo
776 Goodra
777 Klefki
778 Phantump
779 Trevenant
780 PumpkabooAverage Size
781 PumpkabooSmall Size
782 PumpkabooLarge Size
783 PumpkabooSuper Size
784 GourgeistAverage Size
785 GourgeistSmall Size
786 GourgeistLarge Size
787 GourgeistSuper Size
788 Bergmite
789 Avalugg
790 Noibat
791 Noivern
792 Xerneas
793 Yveltal
794 Zygarde50% Forme
795 Diancie
796 DiancieMega Diancie
797 HoopaHoopa Confined
798 HoopaHoopa Unbound
799 Volcanion

In [42]:
# Read a specific location (R,C) by labels
df.loc[df['Type 1'] == 'Grass']

       #                   Name Type 1  ... Speed  Generation  Legendary
0      1              Bulbasaur  Grass  ...    45           1      False
1      2                Ivysaur  Grass  ...    60           1      False
2      3               Venusaur  Grass  ...    80           1      False
3      3  VenusaurMega Venusaur  Grass  ...    80           1      False
48    43                 Oddish  Grass  ...    30           1      False
..   ...                    ...    ...  ...   ...         ...        ...
718  650                Chespin  Grass  ...    38           6      False
719  651              Quilladin  Grass  ...    57           6      False
720  652             Chesnaught  Grass  ...    64           6      False
740  672                 Skiddo  Grass  ...    52           6      False
741  673                 Gogoat  Grass  ...    68           6      False

[70 rows x 12 columns]

## **Sorting/Describing Data**

In [43]:
df.describe()

                #          HP      Attack  ...     Sp. Def       Speed  Generation
count  800.000000  800.000000  800.000000  ...  800.000000  800.000000   800.00000
mean   362.813750   69.258750   79.001250  ...   71.902500   68.277500     3.32375
std    208.343798   25.534669   32.457366  ...   27.828916   29.060474     1.66129
min      1.000000    1.000000    5.000000  ...   20.000000    5.000000     1.00000
25%    184.750000   50.000000   55.000000  ...   50.000000   45.000000     2.00000
50%    364.500000   65.000000   75.000000  ...   70.000000   65.000000     3.00000
75%    539.250000   80.000000  100.000000  ...   90.000000   90.000000     5.00000
max    721.000000  255.000000  190.000000  ...  230.000000  180.000000     6.00000

[8 rows x 8 columns]

In [44]:
df.sort_values('Name', ascending=False)

       #                     Name   Type 1  ... Speed  Generation  Legendary
794  718         Zygarde50% Forme   Dragon  ...    95           6       True
695  634                 Zweilous     Dark  ...    58           5      False
46    41                    Zubat   Poison  ...    55           1      False
631  570                    Zorua     Dark  ...    65           5      False
632  571                  Zoroark     Dark  ...   105           5      False
..   ...                      ...      ...  ...   ...         ...        ...
393  359          AbsolMega Absol     Dark  ...   115           3      False
392  359                    Absol     Dark  ...    75           3      False
68    63                     Abra  Psychic  ...    90           1      False
511  460  AbomasnowMega Abomasnow    Grass  ...    30           4      False
510  460                Abomasnow    Grass  ...    60           4      False

[800 rows x 12 columns]

In [45]:
df.sort_values(['Type 1', 'HP'], ascending=[1,0])

       #                     Name Type 1  ... Speed  Generation  Legendary
520  469                  Yanmega    Bug  ...    95           4      False
698  637                Volcarona    Bug  ...   100           5      False
231  214                Heracross    Bug  ...    85           2      False
232  214  HeracrossMega Heracross    Bug  ...    75           2      False
678  617                 Accelgor    Bug  ...   145           5      False
..   ...                      ...    ...  ...   ...         ...        ...
106   98                   Krabby  Water  ...    50           1      False
125  116                   Horsea  Water  ...    60           1      False
129  120                   Staryu  Water  ...    85           1      False
139  129                 Magikarp  Water  ...    80           1      False
381  349                   Feebas  Water  ...    80           3      False

[800 rows x 12 columns]

## **Making changes to the data**

In [46]:
df.head(5).T

                    0        1         2                      3           4
#                   1        2         3                      3           4
Name        Bulbasaur  Ivysaur  Venusaur  VenusaurMega Venusaur  Charmander
Type 1          Grass    Grass     Grass                  Grass        Fire
Type 2         Poison   Poison    Poison                 Poison         NaN
HP                 45       60        80                     80          39
Attack             49       62        82                    100          52
Defense            49       63        83                    123          43
Sp. Atk            65       80       100                    122          60
Sp. Def            65       80       100                    120          50
Speed              45       60        80                     80          65
Generation          1        1         1                      1           1
Legendary       False    False     False                  False       False

In [48]:
df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
df.head(5).T

                    0        1         2                      3           4
#                   1        2         3                      3           4
Name        Bulbasaur  Ivysaur  Venusaur  VenusaurMega Venusaur  Charmander
Type 1          Grass    Grass     Grass                  Grass        Fire
Type 2         Poison   Poison    Poison                 Poison         NaN
HP                 45       60        80                     80          39
Attack             49       62        82                    100          52
Defense            49       63        83                    123          43
Sp. Atk            65       80       100                    122          60
Sp. Def            65       80       100                    120          50
Speed              45       60        80                     80          65
Generation          1        1         1                      1           1
Legendary       False    False     False                  False       False
Total             318      405       525                    625         309

In [50]:
# Drop the column
df = df.drop(columns=['Total'])
df.head(5).T

                    0        1         2                      3           4
#                   1        2         3                      3           4
Name        Bulbasaur  Ivysaur  Venusaur  VenusaurMega Venusaur  Charmander
Type 1          Grass    Grass     Grass                  Grass        Fire
Type 2         Poison   Poison    Poison                 Poison         NaN
HP                 45       60        80                     80          39
Attack             49       62        82                    100          52
Defense            49       63        83                    123          43
Sp. Atk            65       80       100                    122          60
Sp. Def            65       80       100                    120          50
Speed              45       60        80                     80          65
Generation          1        1         1                      1           1
Legendary       False    False     False                  False       False

In [52]:
# Add a column in a better way
df['Total'] = df.iloc[:,4:10].sum(axis=1)

cols = list(df.columns.values)
df = df[cols[0:4] + [cols[-1]] + cols[4:12]]

df.head(5)

   #                   Name Type 1  ... Speed  Generation  Legendary
0  1              Bulbasaur  Grass  ...    45           1      False
1  2                Ivysaur  Grass  ...    60           1      False
2  3               Venusaur  Grass  ...    80           1      False
3  3  VenusaurMega Venusaur  Grass  ...    80           1      False
4  4             Charmander   Fire  ...    65           1      False

[5 rows x 13 columns]

## **Saving our Data (Exploring into Desired Format**

In [0]:
df.to_csv('modified.csv', index=False)

## **Filtering Data**

In [55]:
df.head().T

                    0        1         2                      3           4
#                   1        2         3                      3           4
Name        Bulbasaur  Ivysaur  Venusaur  VenusaurMega Venusaur  Charmander
Type 1          Grass    Grass     Grass                  Grass        Fire
Type 2         Poison   Poison    Poison                 Poison         NaN
Total             318      405       525                    625         309
HP                 45       60        80                     80          39
Attack             49       62        82                    100          52
Defense            49       63        83                    123          43
Sp. Atk            65       80       100                    122          60
Sp. Def            65       80       100                    120          50
Speed              45       60        80                     80          65
Generation          1        1         1                      1           1
Legendary       False    False     False                  False       False

In [58]:
df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison')]

       #                   Name Type 1  ... Speed  Generation  Legendary
0      1              Bulbasaur  Grass  ...    45           1      False
1      2                Ivysaur  Grass  ...    60           1      False
2      3               Venusaur  Grass  ...    80           1      False
3      3  VenusaurMega Venusaur  Grass  ...    80           1      False
48    43                 Oddish  Grass  ...    30           1      False
49    44                  Gloom  Grass  ...    40           1      False
50    45              Vileplume  Grass  ...    50           1      False
75    69             Bellsprout  Grass  ...    40           1      False
76    70             Weepinbell  Grass  ...    55           1      False
77    71             Victreebel  Grass  ...    70           1      False
344  315                Roselia  Grass  ...    65           3      False
451  406                  Budew  Grass  ...    55           4      False
452  407               Roserade  Grass  ...    90           4      False
651  590                Foongus  Grass  ...    15           5      False
652  591              Amoonguss  Grass  ...    30           5      False

[15 rows x 13 columns]

In [61]:
new_df = df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] > 70)]
print(new_df)

       #                   Name Type 1  ... Speed  Generation  Legendary
2      3               Venusaur  Grass  ...    80           1      False
3      3  VenusaurMega Venusaur  Grass  ...    80           1      False
50    45              Vileplume  Grass  ...    50           1      False
77    71             Victreebel  Grass  ...    70           1      False
652  591              Amoonguss  Grass  ...    30           5      False

[5 rows x 13 columns]

In [65]:
# Filtered data contains index from the previous dataset
# Reset index
new_df.reset_index(drop=True, inplace=True)

new_df

   index    #                   Name  ... Speed Generation  Legendary
0      2    3               Venusaur  ...    80          1      False
1      3    3  VenusaurMega Venusaur  ...    80          1      False
2     50   45              Vileplume  ...    50          1      False
3     77   71             Victreebel  ...    70          1      False
4    652  591              Amoonguss  ...    30          5      False

[5 rows x 14 columns]

In [66]:
# All the names that contain 'Mega'
df.loc[df['Name'].str.contains('Mega')]

       #                       Name    Type 1  ... Speed  Generation  Legendary
3      3      VenusaurMega Venusaur     Grass  ...    80           1      False
7      6  CharizardMega Charizard X      Fire  ...   100           1      False
8      6  CharizardMega Charizard Y      Fire  ...   100           1      False
12     9    BlastoiseMega Blastoise     Water  ...    78           1      False
19    15      BeedrillMega Beedrill       Bug  ...   145           1      False
23    18        PidgeotMega Pidgeot    Normal  ...   121           1      False
71    65      AlakazamMega Alakazam   Psychic  ...   150           1      False
87    80        SlowbroMega Slowbro     Water  ...    30           1      False
102   94          GengarMega Gengar     Ghost  ...   130           1      False
124  115  KangaskhanMega Kangaskhan    Normal  ...   100           1      False
137  127          PinsirMega Pinsir       Bug  ...   105           1      False
141  130      GyaradosMega Gyarados     Water  ...    81           1      False
154  142  AerodactylMega Aerodactyl      Rock  ...   150           1      False
163  150        MewtwoMega Mewtwo X   Psychic  ...   130           1       True
164  150        MewtwoMega Mewtwo Y   Psychic  ...   140           1       True
168  154                   Meganium     Grass  ...    80           2      False
196  181      AmpharosMega Ampharos  Electric  ...    45           2      False
224  208        SteelixMega Steelix     Steel  ...    30           2      False
229  212          ScizorMega Scizor       Bug  ...    75           2      False
232  214    HeracrossMega Heracross       Bug  ...    75           2      False
248  229      HoundoomMega Houndoom      Dark  ...   115           2      False
268  248    TyranitarMega Tyranitar      Rock  ...    71           2      False
275  254      SceptileMega Sceptile     Grass  ...   145           3      False
279  257      BlazikenMega Blaziken      Fire  ...   100           3      False
283  260      SwampertMega Swampert     Water  ...    70           3      False
306  282    GardevoirMega Gardevoir   Psychic  ...   100           3      False
327  302        SableyeMega Sableye      Dark  ...    20           3      False
329  303          MawileMega Mawile     Steel  ...    50           3      False
333  306          AggronMega Aggron     Steel  ...    50           3      False
336  308      MedichamMega Medicham  Fighting  ...   100           3      False
339  310    ManectricMega Manectric  Electric  ...   135           3      False
349  319      SharpedoMega Sharpedo     Water  ...   105           3      False
354  323      CameruptMega Camerupt      Fire  ...    20           3      False
366  334        AltariaMega Altaria    Dragon  ...    80           3      False
387  354        BanetteMega Banette     Ghost  ...    75           3      False
393  359            AbsolMega Absol      Dark  ...   115           3      False
397  362          GlalieMega Glalie       Ice  ...   100           3      False
409  373    SalamenceMega Salamence    Dragon  ...   120           3      False
413  376    MetagrossMega Metagross     Steel  ...   110           3      False
418  380          LatiasMega Latias    Dragon  ...   110           3       True
420  381          LatiosMega Latios    Dragon  ...   110           3       True
426  384      RayquazaMega Rayquaza    Dragon  ...   115           3       True
476  428        LopunnyMega Lopunny    Normal  ...   135           4      False
494  445      GarchompMega Garchomp    Dragon  ...    92           4      False
498  448        LucarioMega Lucario  Fighting  ...   112           4      False
511  460    AbomasnowMega Abomasnow     Grass  ...    30           4      False
527  475        GalladeMega Gallade   Psychic  ...   110           4      False
591  531          AudinoMega Audino    Normal  ...    50           5      False
796  719        DiancieMega Diancie      Rock  ...   110           6       True

[49 rows x 13 columns]

In [67]:
# All the names that do not contain 'Mega'
df.loc[~df['Name'].str.contains('Mega')]

       #                 Name   Type 1  ... Speed  Generation  Legendary
0      1            Bulbasaur    Grass  ...    45           1      False
1      2              Ivysaur    Grass  ...    60           1      False
2      3             Venusaur    Grass  ...    80           1      False
4      4           Charmander     Fire  ...    65           1      False
5      5           Charmeleon     Fire  ...    80           1      False
..   ...                  ...      ...  ...   ...         ...        ...
794  718     Zygarde50% Forme   Dragon  ...    95           6       True
795  719              Diancie     Rock  ...    50           6       True
797  720  HoopaHoopa Confined  Psychic  ...    70           6       True
798  720   HoopaHoopa Unbound  Psychic  ...    80           6       True
799  721            Volcanion     Fire  ...    70           6       True

[751 rows x 13 columns]

In [69]:
# Regex can be used in str.contains()
import re

df.loc[df['Type 1'].str.contains('fire|grass', flags=re.I, regex=True)]

       #                   Name Type 1  ... Speed  Generation  Legendary
0      1              Bulbasaur  Grass  ...    45           1      False
1      2                Ivysaur  Grass  ...    60           1      False
2      3               Venusaur  Grass  ...    80           1      False
3      3  VenusaurMega Venusaur  Grass  ...    80           1      False
4      4             Charmander   Fire  ...    65           1      False
..   ...                    ...    ...  ...   ...         ...        ...
735  667                 Litleo   Fire  ...    72           6      False
736  668                 Pyroar   Fire  ...   106           6      False
740  672                 Skiddo  Grass  ...    52           6      False
741  673                 Gogoat  Grass  ...    68           6      False
799  721              Volcanion   Fire  ...    70           6       True

[122 rows x 13 columns]

In [72]:
# Names that start with 'pi'
df.loc[df['Name'].str.contains('^pi[a-z]*', flags=re.I, regex=True)]

       #                 Name    Type 1  ... Speed  Generation  Legendary
20    16               Pidgey    Normal  ...    56           1      False
21    17            Pidgeotto    Normal  ...    71           1      False
22    18              Pidgeot    Normal  ...   101           1      False
23    18  PidgeotMega Pidgeot    Normal  ...   121           1      False
30    25              Pikachu  Electric  ...    90           1      False
136  127               Pinsir       Bug  ...    85           1      False
137  127    PinsirMega Pinsir       Bug  ...   105           1      False
186  172                Pichu  Electric  ...    60           2      False
219  204               Pineco       Bug  ...    15           2      False
239  221            Piloswine       Ice  ...    50           2      False
438  393               Piplup     Water  ...    40           4      False
558  499              Pignite      Fire  ...    55           5      False
578  519               Pidove    Normal  ...    43           5      False

[13 rows x 13 columns]

## **Conditional Changes**

In [73]:
df.loc[df['Type 1'] == 'Fire', 'Type 1'] = 'Flamer'

df

       #                   Name   Type 1  ... Speed  Generation  Legendary
0      1              Bulbasaur    Grass  ...    45           1      False
1      2                Ivysaur    Grass  ...    60           1      False
2      3               Venusaur    Grass  ...    80           1      False
3      3  VenusaurMega Venusaur    Grass  ...    80           1      False
4      4             Charmander   Flamer  ...    65           1      False
..   ...                    ...      ...  ...   ...         ...        ...
795  719                Diancie     Rock  ...    50           6       True
796  719    DiancieMega Diancie     Rock  ...   110           6       True
797  720    HoopaHoopa Confined  Psychic  ...    70           6       True
798  720     HoopaHoopa Unbound  Psychic  ...    80           6       True
799  721              Volcanion   Flamer  ...    70           6       True

[800 rows x 13 columns]

In [74]:
df.loc[df['Type 1'] == 'Flamer', 'Type 1'] = 'Fire'

df

       #                   Name   Type 1  ... Speed  Generation  Legendary
0      1              Bulbasaur    Grass  ...    45           1      False
1      2                Ivysaur    Grass  ...    60           1      False
2      3               Venusaur    Grass  ...    80           1      False
3      3  VenusaurMega Venusaur    Grass  ...    80           1      False
4      4             Charmander     Fire  ...    65           1      False
..   ...                    ...      ...  ...   ...         ...        ...
795  719                Diancie     Rock  ...    50           6       True
796  719    DiancieMega Diancie     Rock  ...   110           6       True
797  720    HoopaHoopa Confined  Psychic  ...    70           6       True
798  720     HoopaHoopa Unbound  Psychic  ...    80           6       True
799  721              Volcanion     Fire  ...    70           6       True

[800 rows x 13 columns]

In [76]:
# All the Fire Type 1 will become Legendary True
df.loc[df['Type 1'] == 'Fire', 'Legendary'] = True

df

       #                   Name   Type 1  ... Speed  Generation  Legendary
0      1              Bulbasaur    Grass  ...    45           1      False
1      2                Ivysaur    Grass  ...    60           1      False
2      3               Venusaur    Grass  ...    80           1      False
3      3  VenusaurMega Venusaur    Grass  ...    80           1      False
4      4             Charmander     Fire  ...    65           1       True
..   ...                    ...      ...  ...   ...         ...        ...
795  719                Diancie     Rock  ...    50           6       True
796  719    DiancieMega Diancie     Rock  ...   110           6       True
797  720    HoopaHoopa Confined  Psychic  ...    70           6       True
798  720     HoopaHoopa Unbound  Psychic  ...    80           6       True
799  721              Volcanion     Fire  ...    70           6       True

[800 rows x 13 columns]

In [78]:
df.loc[df['Total'] > 500, ['Generation', 'Legendary']] = ['Test 1', 'Test 2']

df

       #                   Name   Type 1  ... Speed  Generation  Legendary
0      1              Bulbasaur    Grass  ...    45           1      False
1      2                Ivysaur    Grass  ...    60           1      False
2      3               Venusaur    Grass  ...    80      Test 1     Test 2
3      3  VenusaurMega Venusaur    Grass  ...    80      Test 1     Test 2
4      4             Charmander     Fire  ...    65           1       True
..   ...                    ...      ...  ...   ...         ...        ...
795  719                Diancie     Rock  ...    50      Test 1     Test 2
796  719    DiancieMega Diancie     Rock  ...   110      Test 1     Test 2
797  720    HoopaHoopa Confined  Psychic  ...    70      Test 1     Test 2
798  720     HoopaHoopa Unbound  Psychic  ...    80      Test 1     Test 2
799  721              Volcanion     Fire  ...    70      Test 1     Test 2

[800 rows x 13 columns]

## **Aggregate Statistics**

In [80]:
df = pd.read_csv('pokemon_data.csv')

df.head().T

                    0        1         2                      3           4
#                   1        2         3                      3           4
Name        Bulbasaur  Ivysaur  Venusaur  VenusaurMega Venusaur  Charmander
Type 1          Grass    Grass     Grass                  Grass        Fire
Type 2         Poison   Poison    Poison                 Poison         NaN
HP                 45       60        80                     80          39
Attack             49       62        82                    100          52
Defense            49       63        83                    123          43
Sp. Atk            65       80       100                    122          60
Sp. Def            65       80       100                    120          50
Speed              45       60        80                     80          65
Generation          1        1         1                      1           1
Legendary       False    False     False                  False       False

In [83]:
df.groupby(['Type 1']).mean().sort_values('Attack', ascending=False)

                   #         HP      Attack  ...       Speed  Generation  Legendary
Type 1                                       ...
Dragon    474.375000  83.312500  112.125000  ...   83.031250    3.875000   0.375000
Fighting  363.851852  69.851852   96.777778  ...   66.074074    3.370370   0.000000
Ground    356.281250  73.781250   95.750000  ...   63.906250    3.156250   0.125000
Rock      392.727273  65.363636   92.863636  ...   55.909091    3.454545   0.090909
Steel     442.851852  65.222222   92.703704  ...   55.259259    3.851852   0.148148
Dark      461.354839  66.806452   88.387097  ...   76.161290    4.032258   0.064516
Fire      327.403846  69.903846   84.769231  ...   74.442308    3.211538   0.096154
Flying    677.750000  70.750000   78.750000  ...  102.500000    5.500000   0.500000
Poison    251.785714  67.250000   74.678571  ...   63.571429    2.535714   0.000000
Water     303.089286  72.062500   74.151786  ...   65.964286    2.857143   0.035714
Ghost     486.500000  64.437500   73.781250  ...   64.343750    4.187500   0.062500
Normal    319.173469  77.275510   73.469388  ...   71.551020    3.051020   0.020408
Grass     344.871429  67.271429   73.214286  ...   61.928571    3.357143   0.042857
Ice       423.541667  72.000000   72.750000  ...   63.458333    3.541667   0.083333
Psychic   380.807018  70.631579   71.456140  ...   81.491228    3.385965   0.245614
Bug       334.492754  56.884058   70.971014  ...   61.681159    3.217391   0.000000
Electric  363.500000  59.795455   69.090909  ...   84.500000    3.272727   0.090909
Fairy     449.529412  74.117647   61.529412  ...   48.588235    4.117647   0.058824

[18 rows x 9 columns]

In [84]:
df.groupby(['Type 1']).sum()

              #    HP  Attack  Defense  ...  Sp. Def  Speed  Generation  Legendary
Type 1                                  ...
Bug       23080  3925    4897     4880  ...     4471   4256         222        0.0
Dark      14302  2071    2740     2177  ...     2155   2361         125        2.0
Dragon    15180  2666    3588     2764  ...     2843   2657         124       12.0
Electric  15994  2631    3040     2917  ...     3243   3718         144        4.0
Fairy      7642  1260    1046     1117  ...     1440    826          70        1.0
Fighting   9824  1886    2613     1780  ...     1747   1784          91        0.0
Fire      17025  3635    4408     3524  ...     3755   3871         167        5.0
Flying     2711   283     315      265  ...      290    410          22        2.0
Ghost     15568  2062    2361     2598  ...     2447   2059         134        2.0
Grass     24141  4709    5125     4956  ...     4930   4335         235        3.0
Ground    11401  2361    3064     2715  ...     2008   2045         101        4.0
Ice       10165  1728    1746     1714  ...     1831   1523          85        2.0
Normal    31279  7573    7200     5865  ...     6245   7012         299        2.0
Poison     7050  1883    2091     1927  ...     1803   1780          71        0.0
Psychic   21706  4026    4073     3858  ...     4918   4645         193       14.0
Rock      17280  2876    4086     4435  ...     3321   2460         152        4.0
Steel     11957  1761    2503     3412  ...     2177   1492         104        4.0
Water     33946  8071    8305     8170  ...     7898   7388         320        4.0

[18 rows x 9 columns]

In [86]:
df['count'] = 1
df

       #                   Name   Type 1  ... Generation  Legendary  count
0      1              Bulbasaur    Grass  ...          1      False      1
1      2                Ivysaur    Grass  ...          1      False      1
2      3               Venusaur    Grass  ...          1      False      1
3      3  VenusaurMega Venusaur    Grass  ...          1      False      1
4      4             Charmander     Fire  ...          1      False      1
..   ...                    ...      ...  ...        ...        ...    ...
795  719                Diancie     Rock  ...          6       True      1
796  719    DiancieMega Diancie     Rock  ...          6       True      1
797  720    HoopaHoopa Confined  Psychic  ...          6       True      1
798  720     HoopaHoopa Unbound  Psychic  ...          6       True      1
799  721              Volcanion     Fire  ...          6       True      1

[800 rows x 13 columns]

In [87]:
df.groupby(['Type 1']).count()['count']

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count, dtype: int64

In [88]:
df.groupby(['Type 1', 'Type 2']).count()['count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64

## **Working with large amounts of data**

In [89]:
for df in pd.read_csv('pokemon_data.csv', chunksize=5):
  print('CHUNK DF')
  print(df)

CHUNK DF
   #                   Name Type 1  ... Speed  Generation  Legendary
0  1              Bulbasaur  Grass  ...    45           1      False
1  2                Ivysaur  Grass  ...    60           1      False
2  3               Venusaur  Grass  ...    80           1      False
3  3  VenusaurMega Venusaur  Grass  ...    80           1      False
4  4             Charmander   Fire  ...    65           1      False

[5 rows x 12 columns]
CHUNK DF
   #                       Name Type 1  ... Speed  Generation  Legendary
5  5                 Charmeleon   Fire  ...    80           1      False
6  6                  Charizard   Fire  ...   100           1      False
7  6  CharizardMega Charizard X   Fire  ...   100           1      False
8  6  CharizardMega Charizard Y   Fire  ...   100           1      False
9  7                   Squirtle  Water  ...    43           1      False

[5 rows x 12 columns]
CHUNK DF
     #                     Name Type 1  ...  Speed  Generation  Legendary
10   8                Wartortle  Water  ...     58           1      False
11   9                Blastoise  Water  ...     78           1      False
12   9  BlastoiseMega Blastoise  Water  ...     78           1      False
13  10                 Caterpie    Bug  ...     45           1      False
14  11                  Metapod    Bug  ...     30           1      False

[5 rows x 12 columns]
CHUNK DF
     #                   Name Type 1  ... Speed  Generation  Legendary
15  12             Butterfree    Bug  ...    70           1      False
16  13                 Weedle    Bug  ...    50           1      False
17  14                 Kakuna    Bug  ...    35           1      False
18  15               Beedrill    Bug  ...    75           1      False
19  15  BeedrillMega Beedrill    Bug  ...   145           1      False

[5 rows x 12 columns]
CHUNK DF
     #                 Name  Type 1  ... Speed  Generation  Legendary
20  16               Pidgey  Normal  ...    56           1      False
21  17            Pidgeotto  Normal  ...    71           1      False
22  18              Pidgeot  Normal  ...   101           1      False
23  18  PidgeotMega Pidgeot  Normal  ...   121           1      False
24  19              Rattata  Normal  ...    72           1      False

[5 rows x 12 columns]
CHUNK DF
     #      Name  Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
25  20  Raticate  Normal     NaN  ...       70     97           1      False
26  21   Spearow  Normal  Flying  ...       31     70           1      False
27  22    Fearow  Normal  Flying  ...       61    100           1      False
28  23     Ekans  Poison     NaN  ...       54     55           1      False
29  24     Arbok  Poison     NaN  ...       79     80           1      False

[5 rows x 12 columns]
CHUNK DF
     #              Name    Type 1  ...  Speed  Generation  Legendary
30  25           Pikachu  Electric  ...     90           1      False
31  26            Raichu  Electric  ...    110           1      False
32  27         Sandshrew    Ground  ...     40           1      False
33  28         Sandslash    Ground  ...     65           1      False
34  29  Nidoran (Female)    Poison  ...     41           1      False

[5 rows x 12 columns]
CHUNK DF
     #            Name  Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
35  30        Nidorina  Poison     NaN  ...       55     56           1      False
36  31       Nidoqueen  Poison  Ground  ...       85     76           1      False
37  32  Nidoran (Male)  Poison     NaN  ...       40     50           1      False
38  33        Nidorino  Poison     NaN  ...       55     65           1      False
39  34        Nidoking  Poison  Ground  ...       75     85           1      False

[5 rows x 12 columns]
CHUNK DF
     #        Name  Type 1 Type 2  ...  Sp. Def  Speed  Generation  Legendary
40  35    Clefairy   Fairy    NaN  ...       65     35           1      False
41  36    Clefable   Fairy    NaN  ...       90     60           1      False
42  37      Vulpix    Fire    NaN  ...       65     65           1      False
43  38   Ninetales    Fire    NaN  ...      100    100           1      False
44  39  Jigglypuff  Normal  Fairy  ...       25     20           1      False

[5 rows x 12 columns]
CHUNK DF
     #        Name  Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
45  40  Wigglytuff  Normal   Fairy  ...       50     45           1      False
46  41       Zubat  Poison  Flying  ...       40     55           1      False
47  42      Golbat  Poison  Flying  ...       75     90           1      False
48  43      Oddish   Grass  Poison  ...       65     30           1      False
49  44       Gloom   Grass  Poison  ...       75     40           1      False

[5 rows x 12 columns]
CHUNK DF
     #       Name Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
50  45  Vileplume  Grass  Poison  ...       90     50           1      False
51  46      Paras    Bug   Grass  ...       55     25           1      False
52  47   Parasect    Bug   Grass  ...       80     30           1      False
53  48    Venonat    Bug  Poison  ...       55     45           1      False
54  49   Venomoth    Bug  Poison  ...       75     90           1      False

[5 rows x 12 columns]
CHUNK DF
     #     Name  Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
55  50  Diglett  Ground     NaN  ...       45     95           1      False
56  51  Dugtrio  Ground     NaN  ...       70    120           1      False
57  52   Meowth  Normal     NaN  ...       40     90           1      False
58  53  Persian  Normal     NaN  ...       65    115           1      False
59  54  Psyduck   Water     NaN  ...       50     55           1      False

[5 rows x 12 columns]
CHUNK DF
     #       Name    Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
60  55    Golduck     Water     NaN  ...       80     85           1      False
61  56     Mankey  Fighting     NaN  ...       45     70           1      False
62  57   Primeape  Fighting     NaN  ...       70     95           1      False
63  58  Growlithe      Fire     NaN  ...       50     60           1      False
64  59   Arcanine      Fire     NaN  ...       80     95           1      False

[5 rows x 12 columns]
CHUNK DF
     #       Name   Type 1    Type 2  ...  Sp. Def  Speed  Generation  Legendary
65  60    Poliwag    Water       NaN  ...       40     90           1      False
66  61  Poliwhirl    Water       NaN  ...       50     90           1      False
67  62  Poliwrath    Water  Fighting  ...       90     70           1      False
68  63       Abra  Psychic       NaN  ...       55     90           1      False
69  64    Kadabra  Psychic       NaN  ...       70    105           1      False

[5 rows x 12 columns]
CHUNK DF
     #                   Name    Type 1  ...  Speed  Generation  Legendary
70  65               Alakazam   Psychic  ...    120           1      False
71  65  AlakazamMega Alakazam   Psychic  ...    150           1      False
72  66                 Machop  Fighting  ...     35           1      False
73  67                Machoke  Fighting  ...     45           1      False
74  68                Machamp  Fighting  ...     55           1      False

[5 rows x 12 columns]
CHUNK DF
     #        Name Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
75  69  Bellsprout  Grass  Poison  ...       30     40           1      False
76  70  Weepinbell  Grass  Poison  ...       45     55           1      False
77  71  Victreebel  Grass  Poison  ...       70     70           1      False
78  72   Tentacool  Water  Poison  ...      100     70           1      False
79  73  Tentacruel  Water  Poison  ...      120    100           1      False

[5 rows x 12 columns]
CHUNK DF
     #      Name Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
80  74   Geodude   Rock  Ground  ...       30     20           1      False
81  75  Graveler   Rock  Ground  ...       45     35           1      False
82  76     Golem   Rock  Ground  ...       65     45           1      False
83  77    Ponyta   Fire     NaN  ...       65     90           1      False
84  78  Rapidash   Fire     NaN  ...       80    105           1      False

[5 rows x 12 columns]
CHUNK DF
     #                 Name    Type 1  ... Speed  Generation  Legendary
85  79             Slowpoke     Water  ...    15           1      False
86  80              Slowbro     Water  ...    30           1      False
87  80  SlowbroMega Slowbro     Water  ...    30           1      False
88  81            Magnemite  Electric  ...    45           1      False
89  82             Magneton  Electric  ...    70           1      False

[5 rows x 12 columns]
CHUNK DF
     #        Name  Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
90  83  Farfetch'd  Normal  Flying  ...       62     60           1      False
91  84       Doduo  Normal  Flying  ...       35     75           1      False
92  85      Dodrio  Normal  Flying  ...       60    100           1      False
93  86        Seel   Water     NaN  ...       70     45           1      False
94  87     Dewgong   Water     Ice  ...       95     70           1      False

[5 rows x 12 columns]
CHUNK DF
     #      Name  Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
95  88    Grimer  Poison     NaN  ...       50     25           1      False
96  89       Muk  Poison     NaN  ...      100     50           1      False
97  90  Shellder   Water     NaN  ...       25     40           1      False
98  91  Cloyster   Water     Ice  ...       45     70           1      False
99  92    Gastly   Ghost  Poison  ...       35     80           1      False

[5 rows x 12 columns]
CHUNK DF
      #               Name   Type 1  ... Speed  Generation  Legendary
100  93            Haunter    Ghost  ...    95           1      False
101  94             Gengar    Ghost  ...   110           1      False
102  94  GengarMega Gengar    Ghost  ...   130           1      False
103  95               Onix     Rock  ...    70           1      False
104  96            Drowzee  Psychic  ...    42           1      False

[5 rows x 12 columns]
CHUNK DF
       #       Name    Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
105   97      Hypno   Psychic     NaN  ...      115     67           1      False
106   98     Krabby     Water     NaN  ...       25     50           1      False
107   99    Kingler     Water     NaN  ...       50     75           1      False
108  100    Voltorb  Electric     NaN  ...       55    100           1      False
109  101  Electrode  Electric     NaN  ...       80    140           1      False

[5 rows x 12 columns]
CHUNK DF
       #       Name    Type 1   Type 2  ...  Sp. Def  Speed  Generation  Legendary
110  102  Exeggcute     Grass  Psychic  ...       45     40           1      False
111  103  Exeggutor     Grass  Psychic  ...       65     55           1      False
112  104     Cubone    Ground      NaN  ...       50     35           1      False
113  105    Marowak    Ground      NaN  ...       80     45           1      False
114  106  Hitmonlee  Fighting      NaN  ...      110     87           1      False

[5 rows x 12 columns]
CHUNK DF
       #        Name    Type 1 Type 2  ...  Sp. Def  Speed  Generation  Legendary
115  107  Hitmonchan  Fighting    NaN  ...      110     76           1      False
116  108   Lickitung    Normal    NaN  ...       75     30           1      False
117  109     Koffing    Poison    NaN  ...       45     35           1      False
118  110     Weezing    Poison    NaN  ...       70     60           1      False
119  111     Rhyhorn    Ground   Rock  ...       30     25           1      False

[5 rows x 12 columns]
CHUNK DF
       #                       Name  Type 1  ... Speed  Generation  Legendary
120  112                     Rhydon  Ground  ...    40           1      False
121  113                    Chansey  Normal  ...    50           1      False
122  114                    Tangela   Grass  ...    60           1      False
123  115                 Kangaskhan  Normal  ...    90           1      False
124  115  KangaskhanMega Kangaskhan  Normal  ...   100           1      False

[5 rows x 12 columns]
CHUNK DF
       #     Name Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
125  116   Horsea  Water     NaN  ...       25     60           1      False
126  117   Seadra  Water     NaN  ...       45     85           1      False
127  118  Goldeen  Water     NaN  ...       50     63           1      False
128  119  Seaking  Water     NaN  ...       80     68           1      False
129  120   Staryu  Water     NaN  ...       55     85           1      False

[5 rows x 12 columns]
CHUNK DF
       #        Name    Type 1   Type 2  ...  Sp. Def  Speed  Generation  Legendary
130  121     Starmie     Water  Psychic  ...       85    115           1      False
131  122    Mr. Mime   Psychic    Fairy  ...      120     90           1      False
132  123     Scyther       Bug   Flying  ...       80    105           1      False
133  124        Jynx       Ice  Psychic  ...       95     95           1      False
134  125  Electabuzz  Electric      NaN  ...       85    105           1      False

[5 rows x 12 columns]
CHUNK DF
       #               Name  Type 1  ... Speed  Generation  Legendary
135  126             Magmar    Fire  ...    93           1      False
136  127             Pinsir     Bug  ...    85           1      False
137  127  PinsirMega Pinsir     Bug  ...   105           1      False
138  128             Tauros  Normal  ...   110           1      False
139  129           Magikarp   Water  ...    80           1      False

[5 rows x 12 columns]
CHUNK DF
       #                   Name  Type 1  ... Speed  Generation  Legendary
140  130               Gyarados   Water  ...    81           1      False
141  130  GyaradosMega Gyarados   Water  ...    81           1      False
142  131                 Lapras   Water  ...    60           1      False
143  132                  Ditto  Normal  ...    48           1      False
144  133                  Eevee  Normal  ...    55           1      False

[5 rows x 12 columns]
CHUNK DF
       #      Name    Type 1 Type 2  ...  Sp. Def  Speed  Generation  Legendary
145  134  Vaporeon     Water    NaN  ...       95     65           1      False
146  135   Jolteon  Electric    NaN  ...       95    130           1      False
147  136   Flareon      Fire    NaN  ...      110     65           1      False
148  137   Porygon    Normal    NaN  ...       75     40           1      False
149  138   Omanyte      Rock  Water  ...       55     35           1      False

[5 rows x 12 columns]
CHUNK DF
       #                       Name Type 1  ... Speed  Generation  Legendary
150  139                    Omastar   Rock  ...    55           1      False
151  140                     Kabuto   Rock  ...    55           1      False
152  141                   Kabutops   Rock  ...    80           1      False
153  142                 Aerodactyl   Rock  ...   130           1      False
154  142  AerodactylMega Aerodactyl   Rock  ...   150           1      False

[5 rows x 12 columns]
CHUNK DF
       #      Name    Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
155  143   Snorlax    Normal     NaN  ...      110     30           1      False
156  144  Articuno       Ice  Flying  ...      125     85           1       True
157  145    Zapdos  Electric  Flying  ...       90    100           1       True
158  146   Moltres      Fire  Flying  ...       85     90           1       True
159  147   Dratini    Dragon     NaN  ...       50     50           1      False

[5 rows x 12 columns]
CHUNK DF
       #                 Name   Type 1  ... Speed  Generation  Legendary
160  148            Dragonair   Dragon  ...    70           1      False
161  149            Dragonite   Dragon  ...    80           1      False
162  150               Mewtwo  Psychic  ...   130           1       True
163  150  MewtwoMega Mewtwo X  Psychic  ...   130           1       True
164  150  MewtwoMega Mewtwo Y  Psychic  ...   140           1       True

[5 rows x 12 columns]
CHUNK DF
       #       Name   Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
165  151        Mew  Psychic     NaN  ...      100    100           1      False
166  152  Chikorita    Grass     NaN  ...       65     45           2      False
167  153    Bayleef    Grass     NaN  ...       80     60           2      False
168  154   Meganium    Grass     NaN  ...      100     80           2      False
169  155  Cyndaquil     Fire     NaN  ...       50     65           2      False

[5 rows x 12 columns]
CHUNK DF
       #        Name Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
170  156     Quilava   Fire     NaN  ...       65     80           2      False
171  157  Typhlosion   Fire     NaN  ...       85    100           2      False
172  158    Totodile  Water     NaN  ...       48     43           2      False
173  159    Croconaw  Water     NaN  ...       63     58           2      False
174  160  Feraligatr  Water     NaN  ...       83     78           2      False

[5 rows x 12 columns]
CHUNK DF
       #      Name  Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
175  161   Sentret  Normal     NaN  ...       45     20           2      False
176  162    Furret  Normal     NaN  ...       55     90           2      False
177  163  Hoothoot  Normal  Flying  ...       56     50           2      False
178  164   Noctowl  Normal  Flying  ...       96     70           2      False
179  165    Ledyba     Bug  Flying  ...       80     55           2      False

[5 rows x 12 columns]
CHUNK DF
       #      Name  Type 1    Type 2  ...  Sp. Def  Speed  Generation  Legendary
180  166    Ledian     Bug    Flying  ...      110     85           2      False
181  167  Spinarak     Bug    Poison  ...       40     30           2      False
182  168   Ariados     Bug    Poison  ...       60     40           2      False
183  169    Crobat  Poison    Flying  ...       80    130           2      False
184  170  Chinchou   Water  Electric  ...       56     67           2      False

[5 rows x 12 columns]
CHUNK DF
       #       Name    Type 1    Type 2  ...  Sp. Def  Speed  Generation  Legendary
185  171    Lanturn     Water  Electric  ...       76     67           2      False
186  172      Pichu  Electric       NaN  ...       35     60           2      False
187  173     Cleffa     Fairy       NaN  ...       55     15           2      False
188  174  Igglybuff    Normal     Fairy  ...       20     15           2      False
189  175     Togepi     Fairy       NaN  ...       65     20           2      False

[5 rows x 12 columns]
CHUNK DF
       #     Name    Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
190  176  Togetic     Fairy  Flying  ...      105     40           2      False
191  177     Natu   Psychic  Flying  ...       45     70           2      False
192  178     Xatu   Psychic  Flying  ...       70     95           2      False
193  179   Mareep  Electric     NaN  ...       45     35           2      False
194  180  Flaaffy  Electric     NaN  ...       60     45           2      False

[5 rows x 12 columns]
CHUNK DF
       #                   Name    Type 1  ... Speed  Generation  Legendary
195  181               Ampharos  Electric  ...    55           2      False
196  181  AmpharosMega Ampharos  Electric  ...    45           2      False
197  182              Bellossom     Grass  ...    50           2      False
198  183                 Marill     Water  ...    40           2      False
199  184              Azumarill     Water  ...    50           2      False

[5 rows x 12 columns]
CHUNK DF
       #       Name Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
200  185  Sudowoodo   Rock     NaN  ...       65     30           2      False

In [90]:
new_df = pd.DataFrame(columns=df.columns)

for df in pd.read_csv('pokemon_data.csv', chunksize=5):
  results = df.groupby(['Type 1']).count()

  new_df = pd.concat([new_df, results])

new_df.head().T

           Fire Grass Fire Water  Bug
#             1     4    4     1    2
Name          1     4    4     1    2
Type 1      NaN   NaN  NaN   NaN  NaN
Type 2        0     4    3     0    0
HP            1     4    4     1    2
Attack        1     4    4     1    2
Defense       1     4    4     1    2
Sp. Atk       1     4    4     1    2
Sp. Def       1     4    4     1    2
Speed         1     4    4     1    2
Generation    1     4    4     1    2
Legendary     1     4    4     1    2